### ISSUE TITLE
OpenSpades binary installation location is wrong

### ISSUE THREAD

**Issue by gitgud-software** [anyc/anyc-overlay#6]
/opt/bin/openspades contains the following script:

```
#! /bin/sh

PWD=$(pwd)

cd /opt/openspades/bin/

./OpenSpades
```

However, the OpenSpades executable is located at /opt/openspades/games/ upon install, at least for me.

On a side note, /opt/openspades/share/applications contains openspades.desktop but that icon should be moved to a place where the system will recognize it exists (/usr/share/applications/) during the install process.

The program will launch normally if launched in /opt/openspades/games/, fortunately.

**Comment by anyc** [comment]
Okay, I just checked and it's not necessary to put everything into /opt/. I updated the ebuild and it works here. Please let me know if there are further issues.
